# Generated by Django 3.1.3 on 2020-12-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Employee_ID',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Phone_Number',
            field=models.TextField(max_length=13),
        ),
    ]
