# Generated by Django 3.1.3 on 2020-12-03 11:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201202_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Phone_Number',
        ),
        migrations.AddField(
            model_name='employees',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Employee_ID',
            field=models.IntegerField(),
        ),
    ]
