# Generated by Django 3.1.3 on 2020-12-03 17:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201203_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Employee_ID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
