# Generated by Django 3.1.3 on 2020-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20201203_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projects',
            field=models.ManyToManyField(to='register.Employees'),
        ),
    ]
