# Generated by Django 3.1.3 on 2020-12-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20201204_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_ID', models.IntegerField()),
                ('Project_Name', models.CharField(max_length=100)),
                ('Project_Manager', models.CharField(max_length=100)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Project_Manager',
            new_name='Project',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='End_Date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Project_ID',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Project_Name',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Start_Date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projects',
        ),
        migrations.AddField(
            model_name='employees',
            name='projects',
            field=models.ManyToManyField(to='register.Projects'),
        ),
    ]
