# Generated by Django 3.1.3 on 2020-12-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20201204_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='projects',
            new_name='Employees_projects',
        ),
    ]
