# Generated by Django 3.1.3 on 2020-12-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20201204_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Designation',
            field=models.CharField(max_length=100),
        ),
    ]
