# Generated by Django 3.1.3 on 2020-12-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20201204_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.AlterField(
            model_name='employees',
            name='Employees_projects',
            field=models.ManyToManyField(to='register.ProjectDetails'),
        ),
    ]
