# Generated by Django 3.1.3 on 2020-12-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20201204_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='Employees_projects',
            field=models.ManyToManyField(to='register.Projects'),
        ),
    ]
